services:
  mongodb:

    image: mongo:6.0

    container_name: mongodb

    ports:
      - "27007:27017"

    volumes:
      - ./mongodb:/data/db

    networks:
      - backend
      
    restart: always

networks:
  backend:
